### ISSUE TITLE
Request to remove a link

### ISSUE THREAD

**Issue by mnaylor375** [keiichiw/a-puzzle-a-day-solver#4]
Hello! We love your A-Puzzle-A-Day solver! We are the inventors of A-Puzzle-A-Day, and very happy you have put a link to our DragonFjord page (www.dragonfjord.com).

We have several international patents on the design: WIPO DM/215118; EUIPO 007690433, which has helped slow the flood of copycat designs filling the market. We see you have put a link to one of these copiers alongside the link to our original, and wonder if you could remove this link? This is company that is knowingly copying our original design with no credit and claiming it is their own.

Thank you!

**Comment by keiichiw** [comment]
Hi, thank you for creating such a wonderful puzzle A-Puzzle-A-Day!
Sure. I just modified the source code so the page will be updated soon.
