### ISSUE TITLE
Feature request (yet another) new board type

### ISSUE THREAD

**Issue by oneillkza** [keiichiw/a-puzzle-a-day-solver#7]
Related to #3 :

![](https://puzzleparadise.net/uploads/cache/IMG_20201127_130032989-800x800.jpg)

https://puzzleparadise.net/listing/puzzle-calendar-solve-for-each-day-of-the-year-cherry-pieces-and-walnut-border/107535

Maybe if I have some free time I'll take a look at this.

**Comment by oneillkza** [comment]
OK first problem -- this one has nine pieces, while the others have eight. So the match statement in `get_blocks` blows chunks, because you can't have an 8-array and a 9-array return in the same match statement. It sounds like using the enum directly in some way may work?

https://www.reddit.com/r/rust/comments/3hfnq6/match_arms_have_incompatible_types_is_there_a/

(Not super familiar with Rust.)

**Comment by keiichiw** [comment]
I don't think I'll support this board by myself because I don't have the puzzle, but pull requests are welcome.
You can see https://github.com/keiichiw/a-puzzle-a-day-solver/pull/1/ to know which files we should update for a new board.

>  you can't have an 8-array and a 9-array return in the same match statement. 

This shouldn't be a problem if you change the array to `Vec`:
```
let pieces = match typ {
  PuzzleType::DragonFjord => {
    // Change fixed-size array to Vec
    vec![HexRect, PentL, PentN, PentP, PentU, PentV, PentY, PentZ]
  }
   ...
};
```
It'll require an extra heap allocation, but it's negligible.

**Comment by oneillkza** [comment]
Oh lol. Glad there's such a simple solution. I had gone down a very unhelpful rabbit hole of discussions over whether to allow variable-length arrays in Rust.

Anyway, please see #8 

I got everything working except the web interface, which runs and shows the options, but doesn't actually return the solution for the correct set.

**Comment by oneillkza** [comment]
Also this is literally my first time coding in Rust, so let me know if anything is deeply wrong in how I've done things.

**Comment by keiichiw** [comment]
It's now available at [the page](https://keiichiw.github.io/a-puzzle-a-day-solver/) as "Tetromino-type Calendar Puzzle". Thanks @oneillkza for your contribution!

**Comment by oneillkza** [comment]
You're most welcome!
